In [4]:
import numpy as np

def load_npz_file(file_path):
    try:
        # 使用NumPy的load函数加载npz文件
        data = np.load(file_path)
        
        # 输出文件中包含的所有数组的名称
        print("Arrays in the file:", list(data.keys()))
        
        # 根据数组名称访问相应的数组数据
        for array_name in data:
            print(f"{array_name}:")
            print(data[array_name])
        
        # 返回加载的数据
        return data
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

# 替换为你的npz文件路径，使用两个反斜杠或者原始字符串
npz_file_path = r"C:\Users\An\pneumoniamnist.npz"

# 调用函数加载npz文件
loaded_data = load_npz_file(npz_file_path)

Arrays in the file: ['train_images', 'val_images', 'test_images', 'train_labels', 'val_labels', 'test_labels']
train_images:
[[[ 92 108 117 ...   5   8   6]
  [129 138 141 ...   4   2   3]
  [141 146 148 ...   0   0   0]
  ...
  [168 180 192 ... 119 115 126]
  [173 184 195 ... 153 139 132]
  [173 185 198 ... 168 154 139]]

 [[115 118 117 ... 123 115 104]
  [130 137 140 ... 146 135 121]
  [134 151 167 ... 152 138 123]
  ...
  [176 180 187 ... 169 151 142]
  [181 185 192 ... 173 163 158]
  [184 189 195 ... 183 176 169]]

 [[149 146 147 ... 128 141 151]
  [171 153 147 ... 149 159 166]
  [172 166 167 ... 162 170 172]
  ...
  [ 95 133 174 ... 159 118 150]
  [139 166 196 ... 185 147 150]
  [181 184 191 ... 188 169 157]]

 ...

 [[ 86  97 103 ...  53  44  44]
  [ 88 102 116 ...  57  46  46]
  [ 96 106 125 ...  74  60  58]
  ...
  [ 43  58  81 ... 147 139 132]
  [ 90 106 127 ... 148 138 130]
  [132 142 153 ... 145 136 129]]

 [[ 14   0   0 ...  96  95  99]
  [ 66  56  65 ... 119 115 118]
  [ 9

In [1]:
import os
os.getcwd()

'C:\\Users\\001'

In [4]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

def load_npz_file(file_path):
    try:
        # Use NumPy's load function to load npz file
        data = np.load(file_path)

        # Output the names of all arrays in the file
        print("Arrays in the file:", list(data.keys()))

        # Use specific keys to access images and labels
        images = data['train_images']
        labels = data['train_labels']

        # Return the loaded data
        return images, labels
    except Exception as e:
        print(f"An error occurred: {e}")
        return None, None

# Replace with your npz file path using two backslashes or a raw string
npz_file_path = r"C:\Users\An\pneumoniamnist.npz"

# Call the function to load the npz file
images, labels = load_npz_file(npz_file_path)

# Assuming 'normal' and 'pneumonia' are the keys in your npz file
X = images
y = labels

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize pixel values to the range [0, 1]
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0

# Define the CNN model
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer=tf.compat.v1.train.AdamOptimizer(), loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"\nTest accuracy: {test_acc}")

# Make predictions on new data
# new_data = ... # Replace with your new data
# predictions = model.predict(new_data)

Arrays in the file: ['train_images', 'val_images', 'test_images', 'train_labels', 'val_labels', 'test_labels']
Epoch 1/10
95/95 [==============================] - 2s 14ms/step - loss: 0.3705 - accuracy: 0.8313 - val_loss: 0.2292 - val_accuracy: 0.9085
Epoch 2/10
95/95 [==============================] - 1s 10ms/step - loss: 0.1958 - accuracy: 0.9187 - val_loss: 0.1783 - val_accuracy: 0.9271
Epoch 3/10
95/95 [==============================] - 1s 10ms/step - loss: 0.1717 - accuracy: 0.9316 - val_loss: 0.1687 - val_accuracy: 0.9390
Epoch 4/10
95/95 [==============================] - 1s 10ms/step - loss: 0.1536 - accuracy: 0.9382 - val_loss: 0.1504 - val_accuracy: 0.9377
Epoch 5/10
95/95 [==============================] - 1s 10ms/step - loss: 0.1420 - accuracy: 0.9422 - val_loss: 0.1648 - val_accuracy: 0.9377
Epoch 6/10
95/95 [==============================] - 1s 11ms/step - loss: 0.1367 - accuracy: 0.9492 - val_loss: 0.1295 - val_accuracy: 0.9456
Epoch 7/10
95/95 [=========================