In [2]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

ModuleNotFoundError: No module named 'tensorflow'

In [4]:
import numpy as np

def load_npz_file("E:\安烨\第四年（实际）\ELEC0134 Applied Machine Learning Systems\coursework\pneumoniamnist.npz"):
    try:
        # 使用NumPy的load函数加载npz文件
        data = np.load(file_path)
        
        # 输出文件中包含的所有数组的名称
        print("Arrays in the file:", list(data.keys()))
        
        # 根据数组名称访问相应的数组数据
        for array_name in data:
            print(f"{array_name}:")
            print(data[array_name])
        
        # 返回加载的数据
        return data
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

# 替换为你自己的npz文件路径
npz_file_path = "path/to/your/file.npz"

# 调用函数加载npz文件
loaded_data = load_npz_file(npz_file_path)

SyntaxError: invalid syntax (2549668021.py, line 3)

In [5]:
import numpy as np

def load_npz_file(file_path):
    try:
        # 使用NumPy的load函数加载npz文件
        data = np.load(file_path)
        
        # 输出文件中包含的所有数组的名称
        print("Arrays in the file:", list(data.keys()))
        
        # 根据数组名称访问相应的数组数据
        for array_name in data:
            print(f"{array_name}:")
            print(data[array_name])
        
        # 返回加载的数据
        return data
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

# 替换为你的npz文件路径，使用两个反斜杠或者原始字符串
npz_file_path = r"E:\安烨\第四年（实际）\ELEC0134 Applied Machine Learning Systems\coursework\pneumoniamnist.npz"

# 调用函数加载npz文件
loaded_data = load_npz_file(npz_file_path)

Arrays in the file: ['train_images', 'val_images', 'test_images', 'train_labels', 'val_labels', 'test_labels']
train_images:
[[[ 92 108 117 ...   5   8   6]
  [129 138 141 ...   4   2   3]
  [141 146 148 ...   0   0   0]
  ...
  [168 180 192 ... 119 115 126]
  [173 184 195 ... 153 139 132]
  [173 185 198 ... 168 154 139]]

 [[115 118 117 ... 123 115 104]
  [130 137 140 ... 146 135 121]
  [134 151 167 ... 152 138 123]
  ...
  [176 180 187 ... 169 151 142]
  [181 185 192 ... 173 163 158]
  [184 189 195 ... 183 176 169]]

 [[149 146 147 ... 128 141 151]
  [171 153 147 ... 149 159 166]
  [172 166 167 ... 162 170 172]
  ...
  [ 95 133 174 ... 159 118 150]
  [139 166 196 ... 185 147 150]
  [181 184 191 ... 188 169 157]]

 ...

 [[ 86  97 103 ...  53  44  44]
  [ 88 102 116 ...  57  46  46]
  [ 96 106 125 ...  74  60  58]
  ...
  [ 43  58  81 ... 147 139 132]
  [ 90 106 127 ... 148 138 130]
  [132 142 153 ... 145 136 129]]

 [[ 14   0   0 ...  96  95  99]
  [ 66  56  65 ... 119 115 118]
  [ 9

In [7]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Load your PneumoniaMNIST dataset and perform necessary preprocessing

# Define a simple CNN model
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # Sigmoid activation for binary classification
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=10, validation_data=(val_images, val_labels))

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Test accuracy: {test_acc}')

NameError: name 'train_images' is not defined

In [8]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Load and preprocess your PneumoniaMNIST dataset
# Replace the following lines with your actual data loading and preprocessing code
# train_images, train_labels = load_and_preprocess_train_data()
# val_images, val_labels = load_and_preprocess_validation_data()
# test_images, test_labels = load_and_preprocess_test_data()

# Define a simple CNN model
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # Sigmoid activation for binary classification
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
# Make sure to replace train_images, train_labels, val_images, val_labels with your actual data
model.fit(train_images, train_labels, epochs=10, validation_data=(val_images, val_labels))

# Evaluate the model on the test set
# Make sure to replace test_images, test_labels with your actual test data
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Test accuracy: {test_acc}')

NameError: name 'train_images' is not defined

In [9]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Load and preprocess your PneumoniaMNIST dataset
# Replace the following lines with your actual data loading and preprocessing code
# For example purposes, let's assume you have a function load_and_preprocess_data() that returns the processed data
train_images, train_labels = load_and_preprocess_data("train")
val_images, val_labels = load_and_preprocess_data("val")
test_images, test_labels = load_and_preprocess_data("test")

# Define a simple CNN model
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # Sigmoid activation for binary classification
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=10, validation_data=(val_images, val_labels))

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Test accuracy: {test_acc}')

NameError: name 'load_and_preprocess_data' is not defined

In [10]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Replace the following lines with your actual data loading and preprocessing code
# For example purposes, let's assume you have a function load_and_preprocess_data() that returns the processed data
def load_and_preprocess_data(split):
    # Your data loading and preprocessing code here
    # Return processed images and labels
    return processed_images, processed_labels

# Load and preprocess your PneumoniaMNIST dataset
train_images, train_labels = load_and_preprocess_data("train")
val_images, val_labels = load_and_preprocess_data("val")
test_images, test_labels = load_and_preprocess_data("test")

# Define a simple CNN model
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # Sigmoid activation for binary classification
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=10, validation_data=(val_images, val_labels))

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Test accuracy: {test_acc}')

NameError: name 'processed_images' is not defined

In [11]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Replace the following lines with your actual data loading and preprocessing code
# For example purposes, let's assume you have a function load_and_preprocess_data() that returns the processed data
def load_and_preprocess_data(split):
    # Your data loading and preprocessing code here
    # For illustration purposes, creating dummy processed data
    processed_images = ...  # Replace with your actual processed images
    processed_labels = ...  # Replace with your actual processed labels
    return processed_images, processed_labels

# Load and preprocess your PneumoniaMNIST dataset
train_images, train_labels = load_and_preprocess_data("train")
val_images, val_labels = load_and_preprocess_data("val")
test_images, test_labels = load_and_preprocess_data("test")

# Define a simple CNN model
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # Sigmoid activation for binary classification
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=10, validation_data=(val_images, val_labels))

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Test accuracy: {test_acc}')

ValueError: Failed to find data adapter that can handle input: <class 'ellipsis'>, <class 'ellipsis'>

In [12]:
ValueError                                Traceback (most recent call last)
Cell In[11], line 34
     31 model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
     33 # Train the model
---> 34 model.fit(train_images, train_labels, epochs=10, validation_data=(val_images, val_labels))
     36 # Evaluate the model on the test set
     37 test_loss, test_acc = model.evaluate(test_images, test_labels)

File ~\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File ~\anaconda3\Lib\site-packages\keras\src\engine\data_adapter.py:1105, in select_data_adapter(x, y)
   1102 adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
   1103 if not adapter_cls:
   1104     # TODO(scottzhu): This should be a less implementation-specific error.
-> 1105     raise ValueError(
   1106         "Failed to find data adapter that can handle input: {}, {}".format(
   1107             _type_name(x), _type_name(y)
   1108         )
   1109     )
   1110 elif len(adapter_cls) > 1:
   1111     raise RuntimeError(
   1112         "Data adapters should be mutually exclusive for "
   1113         "handling inputs. Found multiple adapters {} to handle "
   1114         "input: {}, {}".format(adapter_cls, _type_name(x), _type_name(y))
   1115     )

ValueError: Failed to find data adapter that can handle input: <class 'ellipsis'>, <class 'ellipsis'>


SyntaxError: invalid syntax (3489684229.py, line 1)

In [13]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Replace the following lines with your actual data loading and preprocessing code
# For example purposes, let's assume you have a function load_and_preprocess_data() that returns the processed data
def load_and_preprocess_data(split):
    # Your data loading and preprocessing code here
    # Replace the following lines with your actual data loading code
    processed_images = ...  # Replace with your actual processed images
    processed_labels = ...  # Replace with your actual processed labels
    return processed_images, processed_labels

# Load and preprocess your PneumoniaMNIST dataset
train_images, train_labels = load_and_preprocess_data("train")
val_images, val_labels = load_and_preprocess_data("val")
test_images, test_labels = load_and_preprocess_data("test")

# Ensure that the data is in the correct format (NumPy arrays or TensorFlow tensors)
print(type(train_images))  # It should print <class 'numpy.ndarray'> or <class 'tensorflow.Tensor'>

# Define a simple CNN model
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # Sigmoid activation for binary classification
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=10, validation_data=(val_images, val_labels))

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Test accuracy: {test_acc}')

<class 'ellipsis'>


ValueError: Failed to find data adapter that can handle input: <class 'ellipsis'>, <class 'ellipsis'>

In [14]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Replace the following lines with your actual data loading and preprocessing code
# For example purposes, let's assume you have a function load_and_preprocess_data() that returns the processed data
def load_and_preprocess_data(split):
    # Your data loading and preprocessing code here
    # Replace the following lines with your actual data loading code
    processed_images = ...  # Replace with your actual processed images
    processed_labels = ...  # Replace with your actual processed labels
    return processed_images, processed_labels

# Load and preprocess your PneumoniaMNIST dataset
train_images, train_labels = load_and_preprocess_data("train")
val_images, val_labels = load_and_preprocess_data("val")
test_images, test_labels = load_and_preprocess_data("test")

# Ensure that the data is in the correct format (NumPy arrays or TensorFlow tensors)
# Print the types of your data to verify
print(type(train_images))
print(type(train_labels))

# Define a simple CNN model
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # Sigmoid activation for binary classification
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=10, validation_data=(val_images, val_labels))

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Test accuracy: {test_acc}')

<class 'ellipsis'>
<class 'ellipsis'>


ValueError: Failed to find data adapter that can handle input: <class 'ellipsis'>, <class 'ellipsis'>

In [15]:
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import layers, models

def load_npz_file(file_path):
    try:
        # 使用NumPy的load函数加载npz文件
        data = np.load(file_path)
        
        # 输出文件中包含的所有数组的名称
        print("Arrays in the file:", list(data.keys()))
        
        # 根据数组名称访问相应的数组数据
        for array_name in data:
            print(f"{array_name}:")
            print(data[array_name])
        
        # 返回加载的数据
        return data['images'], data['labels']  # 返回特定数组的数据
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

# 替换为你的npz文件路径，使用两个反斜杠或者原始字符串
npz_file_path = r"E:\安烨\第四年（实际）\ELEC0134 Applied Machine Learning Systems\coursework\pneumoniamnist.npz"

# 调用函数加载npz文件
images, labels = load_npz_file(npz_file_path)

# 数据集的拆分，80% 用于训练，10% 用于验证，10% 用于测试
train_images, test_images, train_labels, test_labels = train_test_split(images, labels, test_size=0.2, random_state=42)
train_images, val_images, train_labels, val_labels = train_test_split(train_images, train_labels, test_size=0.2, random_state=42)

# 定义简单的CNN模型
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # Sigmoid activation for binary classification
])

# 编译模型
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 训练模型
model.fit(train_images, train_labels, epochs=10, validation_data=(val_images, val_labels))

# 在测试集上评估模型
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Test accuracy: {test_acc}')

Arrays in the file: ['train_images', 'val_images', 'test_images', 'train_labels', 'val_labels', 'test_labels']
train_images:
[[[ 92 108 117 ...   5   8   6]
  [129 138 141 ...   4   2   3]
  [141 146 148 ...   0   0   0]
  ...
  [168 180 192 ... 119 115 126]
  [173 184 195 ... 153 139 132]
  [173 185 198 ... 168 154 139]]

 [[115 118 117 ... 123 115 104]
  [130 137 140 ... 146 135 121]
  [134 151 167 ... 152 138 123]
  ...
  [176 180 187 ... 169 151 142]
  [181 185 192 ... 173 163 158]
  [184 189 195 ... 183 176 169]]

 [[149 146 147 ... 128 141 151]
  [171 153 147 ... 149 159 166]
  [172 166 167 ... 162 170 172]
  ...
  [ 95 133 174 ... 159 118 150]
  [139 166 196 ... 185 147 150]
  [181 184 191 ... 188 169 157]]

 ...

 [[ 86  97 103 ...  53  44  44]
  [ 88 102 116 ...  57  46  46]
  [ 96 106 125 ...  74  60  58]
  ...
  [ 43  58  81 ... 147 139 132]
  [ 90 106 127 ... 148 138 130]
  [132 142 153 ... 145 136 129]]

 [[ 14   0   0 ...  96  95  99]
  [ 66  56  65 ... 119 115 118]
  [ 9

TypeError: cannot unpack non-iterable NoneType object